### ISSUE TITLE
Segmentation linear evaluation protocol & smooth segmentation mask

### ISSUE THREAD

**Issue by SimJeg** [bytedance/ibot#10]
Hello,

It is not very clear for me how the linear segmentation protocol works. I understand that the input image is rescale to 512x512 or 640x640 (see [here](https://github.com/bytedance/ibot/tree/main/evaluation/semantic_segmentation/configs/linear)) and then a linear classifier is trained on the tokens at 4 different blocks (concatenation ?). 

As tokens are 16x16 patches, is it correct to say that for a 512x512 image, the output segmentation will be 32x32 and would hence result in a coarse segmentation mask ? What would be the most natural way to obtain a smooth segmentation mask at a pixel level using iBOT models without learning any upscaling layer (e.g. upscale input image, interpolate tokens etc.) ? 

Thank you

**Comment by taokong** [comment]
Yes. In iBOT the coarse segmentation mask is directly upsampled using bilinear interpolation. For more information, please refer to [encoder_decoder.py#L200](https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/segmentors/encoder_decoder.py#L200)
