### ISSUE TITLE
100 or 300 epoch training

### ISSUE THREAD

**Issue by Trent-tangtao** [bytedance/ibot#11]
Hello,
       Have you train iBOT in shorter training time, eg.100epoch or 300epoch,  can you share me these hyper-parameters? Follow DINO,  I set `python -m torch.distributed.launch --nproc_per_node=8 --master_port=29500\
        main_ibot.py \
        --arch vit_small \
        --output_dir ibot_100epoch \
        --data_path imagenet/train \
        --batch_size_per_gpu 64 \
        --local_crops_number 8 \
        --saveckp_freq 10\
        --shared_head true \
        --epochs 100\
        --out_dim 8192`,  I don't know if this is reasonable

**Comment by shallowtoil** [comment]
Hi,

You should follow the args of 800-epoch pre-trained ViT-S/16 [here](https://lf3-nlp-opensource.bytetos.com/obj/nlp-opensource/archive/2022/ibot/vits_16/args.txt) and set `--epochs 300`. Your given args should also be added with `--pred_ratio 0 0.3 --pred_ratio_var 0 0.2 --local_crops_number 10`.

**Comment by Trent-tangtao** [comment]
> 

Got it, thanks for your kind reply!
