### ISSUE TITLE
detection log

### ISSUE THREAD

**Issue by czczup** [bytedance/ibot#13]
Hi, thank you for your outstanding work.
Can you provide the log of detection?

**Comment by shallowtoil** [comment]
Hi,

ViT-S/16: [det](https://drive.google.com/file/d/1CCVeQvFe503qP3XxU25rjxoP0w1Tsdzt/view?usp=sharing), [seg](https://drive.google.com/file/d/1kZYjZw8nf7ocSZfwlCvlFPVMivwonoZN/view?usp=sharing)
ViT-B/16: [det](https://drive.google.com/file/d/17Qvm_Z0sx2yfMI4MmsscJMheNd9AjQFm/view?usp=sharing), [seg](https://drive.google.com/file/d/1J25fncaUFNw8KSMoWJ9TMGG26aPvnbaK/view?usp=sharing)

**Comment by czczup** [comment]
> Hi,
> 
> ViT-S/16: [det](https://drive.google.com/file/d/1CCVeQvFe503qP3XxU25rjxoP0w1Tsdzt/view?usp=sharing), [seg](https://drive.google.com/file/d/1kZYjZw8nf7ocSZfwlCvlFPVMivwonoZN/view?usp=sharing) ViT-B/16: [det](https://drive.google.com/file/d/1fljOnT-pCRUoHWs8Fgmgm4Jcah1n88Hp/view?usp=sharing), [seg](https://drive.google.com/file/d/1J25fncaUFNw8KSMoWJ9TMGG26aPvnbaK/view?usp=sharing)

Thanks!
