### ISSUE TITLE
Patch size 8

### ISSUE THREAD

**Issue by SimJeg** [bytedance/ibot#14]
Hello, 

DINO reports excellent results using a patch size of 8 (+2.7 top1 accuracy on i1k for ViT-S and +1.9 for ViT-B, better segmentation results). Have you considered this setting ? 

Overall do you consider doing additional experiments using iBOT ?

Best,
Simon

**Comment by jensenzhoujh** [comment]
Hi @SimJeg,

Sorry for the late reply. No, we do not plan to scale iBOT for a larger sequence length. I think the performance gain should be valid with ViT-S/8 or ViT-B/8. You could try to run the experiment yourself with a few arguments changed for models with a patch size of 8 following DINO's args. Results are welcomed!
