### ISSUE TITLE
checkpoint not saved by master

### ISSUE THREAD

**Issue by luuuyi** [bytedance/ibot#15]
as your code describe, https://github.com/bytedance/ibot/blob/3302b63fc7e287afc68601cb1dc2f0c311af8e3b/main_ibot.py#L358
in ddp training, every processor(GPU) would save an checkpoint model in disk, this behaviou may cause duplicate writing problem and saved checkpoint can not be load by `torch.load` successfully

**Comment by jensenzhoujh** [comment]
Hi,

Thanks for your pointer! Problem fixed.

**Comment by gaoypeng** [comment]
hi, could you please tell me how to fix this problem?
Thanks so much !

**Comment by jensenzhoujh** [comment]
> hi, could you please tell me how to fix this problem? Thanks so much !

Hi,

Check the following line: https://github.com/bytedance/ibot/blob/da316d82636a7a7356835ef224b13d5f3ace0489/main_ibot.py#L358
