### ISSUE TITLE
large batch size training

### ISSUE THREAD

**Issue by guangdongliang** [bytedance/ibot#17]
when training dino with total batch size 64\*8\*8( 8-nodes ) for large dataset(40M), the model collapse after a few epochs (same issue in [link](https://github.com/facebookresearch/dino/issues/43#issuecomment-846385852)).  ibot train imagenet-22k with batch size 51\*8\*5, and the training process is very stable. have you train with larger batch size ? (for example 51\*8\*8)

**Comment by jensenzhoujh** [comment]
Hi @guangdongliang,

I trained ViT-B/16 on IN-22k with batch size 4096 once and the training was stable. Also, what is the phenomenon of "model collapse" you mentioned (e.g., loss nan, loss converges to 0, small batch-level feature std, ...)? My experience of easing training instability is, for example, enlarging warmup epochs, tweaking ema momentum, or using smaller opt beta2 for AdamW (0.999 by default, decreasing it if the training is unstable)...
