### ISSUE TITLE
question about imagenet 1% logist regression

### ISSUE THREAD

**Issue by haohang96** [bytedance/ibot#21]
hello, I use the eval_logistic_regression.py (lambd=0.1) to evaluate the provided vit-small model but can only get 58.0 val top-1 acc with 1% data, but 65.9 in your paper.Thanks for your help!

Start the logistic regression.
Matrix X, n=12811, p=384
Switching to regular solver, problem is well conditioned
*********************************
Catalyst Accelerator
MISO Solver
Incremental Solver with uniform sampling
Lipschitz constant: 0.25
Multiclass logistic Loss is used
L2 regularization
Epoch: 10, primal objective: 6.90561, time: 211.912
Best relative duality gap: 0.000430669
Time elapsed : 212.632
Logistic regression result: Acc: 0.58044

**Comment by jensenzhoujh** [comment]
Hi,

Are you able to re-produce the results of the DINO models?

**Comment by jensenzhoujh** [comment]
Close this for now. Feel free to re-open it.
