### ISSUE TITLE
1% semi-sup evaluation on IN1k

### ISSUE THREAD

**Issue by merlinarer** [bytedance/ibot#24]
Hello, thank you for your sharing
Could you please provide the log of 1% semi-sup evaluation on IN1k, so that I can check my reproducing?

**Comment by jensenzhoujh** [comment]
Hi @merlinarer,

I'm no longer able to access this log. Are you able to reproduce the results following the [instructions](https://github.com/bytedance/ibot/tree/main/evaluation#semi-supervised-classification-on-imagenet)?

**Comment by jensenzhoujh** [comment]
Close it for now. Feel free to re-open.
