### ISSUE TITLE
Linear semantic segmentation with ViT-L models

### ISSUE THREAD

**Issue by Adrien987k** [bytedance/ibot#28]
Hi,

I was wondering if you had evaluated the ViT-L pretrained on ImageNet1k and ViT-L pretrained on ImageNet22k on the linear semantic segmentation benchmark on ADE20k, similar to column 3 of right table of Table 6 in the paper ? 
If yes, can you share the results and the corresponding log files ?

Thanks!

**Comment by jensenzhoujh** [comment]
Hi @Adrien987k,

I haven't tried those experiments.
