### ISSUE TITLE
Attention Map visualizations

### ISSUE THREAD

**Issue by ucasligang** [bytedance/ibot#5]
Hi, thank you for the great work. 
Recently we plan to make some improvements on the basis of this work. But when we visualized the attention map, we found that it did not show as amazing results as in the paper.  We think there may be some details that we haven’t noticed. Could you please tell me the pre-training model used for visualization and some settings(like threshold, patch_size,  image_size) shown in the paper?
Looking forward to your response!

Sincerely,
Gang Li

**Comment by shallowtoil** [comment]
Hi, Gang

We use 800-epoch pre-trained ViT-S/16 with default hyper-parameters in `visualize_attention.py` scripts. The results should be reproduced by running the following command:
```
./analysis/visualize_attn_map.sh \
  --pretrained_weights $PRETRAINED \
  --output_dir $OUTPUT \
  --data_path data/imagenet/val
```
