### ISSUE TITLE
About Swin-V1 and Swin-V2

### ISSUE THREAD

**Issue by SimJeg** [bytedance/ibot#9]
Hello,

You present very good results with Swin-T/7 and Swin-T/14 and I was wondering why you did not scale these experiments similarly to ViT ? 

Microsoft team should at one point release Swin V2 ([arxiv pdf](https://arxiv.org/pdf/2111.09883.pdf)) which among others get SoTA results on segmentation tasks. Do you plan to experiment with this architecture too ? 

Thank you for your work !

**Comment by shallowtoil** [comment]
Hi,

We are not planning to scale up for Swin Transformer for the time being. In our trials, pre-training with Swin-T requires training subtleties like `--pred_start_epoch 50` to stabilize the pre-training, which is similarly used in the [EsViT](https://arxiv.org/abs/2106.09785) paper. Pre-training with larger models may require a more tailored adjustment that we have not experimented with. But results with Swin-V1 and Swin-V2 is definitely welcomed!
